/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 untitled.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('./untitled.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 2.274]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.New_Object_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.New_Object_2.geometry} material={materials['Material.002']} />
      </group>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Metal Bronze Dixon']} position={[0, 0.973, -0.792]} rotation={[-1.6, 0, 0]} scale={[0.096, 0.015, 0.096]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.003']} position={[-0.002, 0.955, 0.091]} rotation={[-Math.PI / 2, 0, 0]} scale={0.148} />
      <mesh geometry={nodes.Plane002.geometry} material={materials['Material.005']} position={[-0.175, 0.975, 0.091]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.116, 0.117, 0.117]} />
      <mesh geometry={nodes.Plane003.geometry} material={materials['Material.004']} position={[-0.204, 0.958, 0.091]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.164, 0.165, 0.165]} />
    </group>
  )
}

useGLTF.preload('./untitled.gltf')
